export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const FETCH_MORE_CATEGORIES = 'FETCH_MORE_CATEGORIES';



export const STATE_GAME = 'START_GAME';
export const RESET_GAME = 'RESET_GAME';

export const NEW_QUESTION_CARD = 'NEW_QUESTION_CARD';
export const SET_NEW_QUESTION_CARDS = 'SET_NEW_QUESTION_CARDS';



//SELECTED CATEGORY
export const SELECTED_CATEGORY_COMPLETED = 'SELECTED_CATEGORY_COMPLETED';
export const SET_PROGRESS_PROGRESSBAR = 'SET_PROGRESS_PROGRESSBAR';
export const FETCH_SELECTED_CATEGORY = 'FETCH_SELECTED_CATEGORY';
export const FETCH_SELECTED_CATEGORY_FAIL = 'FETCH_SELECTED_CATEGORY_FAIL';
export const RESET_SELECTED_CATEGORY = 'RESET_SELECTED_CATEGORY';

//TRIVIAMAIN
export const COMPLETED_CATEGORY = 'ADD_TOTAL_SCORE';
export const GET_PLAYER_ANSWER = 'GET_PLAYER_ANSWER';
export const POST_PLAYER_SUCCESS = 'POST_PLAYER_SUCCESS';
export const POST_PLAYER_FAIL = 'POST_PLAYER_FAIL';
export const FETCH_LOGGED_IN_PLAYER_SUCCESS_FROM_AUTH = 'FETCH_LOGGED_IN_PLAYER_SUCCESS_FROM_AUTH';
export const TRIVIA_SELECTED_CATEGORY_COMPLETED = 'TRIVIA_SELECTED_CATEGORY_COMPLETED';

//AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const FETCH_LOGGED_IN_PLAYER_FAIL = 'FETCH_LOGGED_IN_PLAYER_FAIL';
export const AUTH_CLEAR_STATE_TO_TRIVIA = 'AUTH_CLEAR_STATE_TO_TRIVIA';







export const MOCK = 'MOCK';