export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const FETCH_MORE_CATEGORIES = 'FETCH_MORE_CATEGORIES';

export const FETCH_SELECTED_CATEGORY = 'FETCH_SELECTED_CATEGORY';
export const FETCH_SELECTED_CATEGORY_FAIL = 'FETCH_SELECTED_CATEGORY_FAIL';

export const GET_PLAYER_ANSWER = 'GET_PLAYER_ANSWER';

export const STATE_GAME = 'START_GAME';
export const RESET_GAME = 'RESET_GAME';

export const NEW_QUESTION_CARD = 'NEW_QUESTION_CARD';
export const SET_NEW_QUESTION_CARDS = 'SET_NEW_QUESTION_CARDS';

export const SET_PROGRESS_PROGRESSBAR = 'SET_PROGRESS_PROGRESSBAR';
export const SELECTED_CATEGORY_COMPLETED = 'SELECTED_CATEGORY_COMPLETED';

export const ADD_TOTAL_SCORE = 'ADD_TOTAL_SCORE';




